import { memo, useEffect, useRef, useState } from 'react'
import Panel from '../ui/Panel'
import { subscribe } from '../utils/raf-coordinator'

// Frame-Loop laeuft ueber den zentralen raf-coordinator (siehe AUDIT_FINDINGS.md H-05).

const EARTH_BASE64 = 'UklGRnQEAABXRUJQVlA4IGgEAACwHACdASoAAYAAPm02l0ikIyIhI9RJSIANiWdu4XPw3WCa6LZn8qt9UY+ELzHfQB/P90N/g98A/uO+Of2DeAP//1r/RP+2drtkH+4UQLuJ0BdsI4B/NuID8H/vPmX8QMdH7zf5f+P3wC/wcJIAN/ZABv7H/hbPzZCYMtMJxbh7BPBZUajnlWc/odAofN/ytItCJc7VQjOdKJEf4wDs5mwSkGzNLb6xwMv/7fz3h/asmq9gpRyalgX1FsUd1x4Ns6RKE1GYL2IXNagdQAb84FRqpbSUH8bzZruVaCdfrzwuX3aWGqQdUWVGsqQAb+oAAP7+UX3/8er1J8q/wOf/49t/49t/49t/+PPOi3s4lCAY50ssB8bFuaPA9RHAvsjjkr0hVoD4+QCCirzRC13shAh3zXDNFVk3MHhlEYPSOpCa+JALDLu4X7snBdI2wnO6pIpwsVxaB+DfwVPw5D9dfNn/MgWdW/qpAPllzcuJZMYvN+lYH9i97ubql7c2f30KyCqUtRPeltR+a6F3Kw+1RsVeVuSPY/jSZe9Vqjn3DOoGfjBAlQit3cbOmEgWytHzWYXR1MY8mqa5KsGKq6WburEfuk5/CcmuagxOIAc40cY0hW1r9ZVnQJUxWSYD9tWVQ6Bwf9buJlj2GvgKDfOl2VTiTIGKmXSeC3Al/Hpp304taxspDNsDkK6LbPn0uK0rAqzRJluNRvuzzmPGn9DJ7gs86zpxsLCCiu9qyt2nEwMdwdT86qD37ubQcYrNUr2dAmVl5zV/gmyo2FTIVKCRxLjP2NnA/DVEAb+CyYtFsW+1kXxCut372VaJEciaIlkPOCX+4DHahW+9nez6e+3rSBROQtsZlltJxhhnDxYJAHBWvOY3dH5oOrISNzTKYyL4sgZZ+4v/glBQtJ2BMQUHn9H70nHyoKJet9KGHjfaLj1SR/MqQDtaKuHW1zC2dpcWfSQjmrD4HWgg7MaeSk3p2X/6CR6LLK9wFigGL9oWPiWsHEmf9xdL26kbZ1QX6N8D9gViStFznJv0ZUE/AXaklYa6hf1lRNeH/Be2RCUvY8qfxZZXolPED72WCYf2pma2ILDzUxcfBE3PS4oyiOeJsXE//Dmq8JBDMqKPddcmglmeTcTzFBeJWHrR6K8l3Aedd0GJMgYqZQY4NHSIzROXVy/WxHo5V+WTHt+x5jNraN1udu64fdB3gCv3Z+5jLLs0LEkZDqWTH7RAYjJ8qEAD46XLDGJJYSID83cNmWtCMmCUXgI4ehFo9kWG1LtKX5YTSY48L9wqGeMn2wt45RxTmu3GZSf/AS9YF3DSsJ7JJIwR8iHVVdSt3dTTTXPf3eDRYnXVOrxxrS5KA3E6OtfhODHN5JpSlKIZ3uuiWcXW1koyZMEGZd2LxeRC3meYbTr8F2sSARIb1ToraJd9Naka/fVRkZj7JDTUb1qD3C3OlH9v5nhwrJh4iXdnD6/8oTrJN//Am3tQpYZQ7LmigkzqVloltrOYgJEc0XdLI9mO6sqwbcy7tEdD+SpN4u71wQXOVF+BuUCRv5reJjO0+eZDmtozS1wnNsyg22Psjpt/BAAzuHjyYUDpebsIfPFZNdTeYR9dLZZmAdovRGuOumyYW6NsnwwUB6pbWje7O4E0p4Q/n6/jRgRXIhZImuO5Du804ZzJ8vU6sHAbnG+2zfA8/Ns0gMMT8cY6RjpaDsxAo7LYv+3ApZzWwb33nVME+vhBqgaZJVpyV4bED7SAIvb7QQdKTAEic+LxM6c2w6N+LSWvJaY5EGu3u/uA9trsH5iZJAyclJj2gWTufgCYfsBfEvUKi0wcCTJDs5oh8EllB4ItQBDtXwS4lE3JHZ/LvkdDoKXbh1dMtAZ0FPKQt6Nj4qxbUhzgTwk40+VQwMCkKUyqKgU9vSMIQjxTaRFWXLvgqOa+/3YOk1NIMj047XUvexO+KAmdjtcb83kiQ/JqGLIyu30fwl9AdFlPYP5WGlkX/AUF0glccNtIlDrwXEtfNYjwq6qUh1q1KCsm3nLCPypX4gaPvTmqWD2075x32yQPVFuiJkdlCL1H44knM0TwDBYTrFYzs0jsTfvlXuuLhfLuden5nWaICIMCvVO6mP8UtgQK1tuDLvBvFNcB0Dfj0csi8WvYmyD38ysgJODsJYK4Uao7Tus0Npia9Hi6hmsRZyspwWWt7KcWuGhV1KKHbaVb/I94TJMytzbJ4okTYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099pZ8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYp1syBl35C5gqYkurA0fulMKRW3ogFzQm6zN0ubto4HLSu96+u/unXqMVKybRYm2dMuSO3YlYJQYsvlwNjyG3+BqiXWrMqq8iecJW6e/aebzFeobGV5GKOfOAgCA2jAfJx9WgvamxqsAswzXoNHcblClc9sWR7PfIBfUUlO3cgU6mY5qN7o1c6REK8u4E3YBfeWt6Ga4MIESaOi3eacKwUdjrrduRteSYoc/zjvNvgQK8yy+Ll9LZOgT+lvn2Jl3hcPC0WZPl7oqpqvitKBJoBqNe8dSiyrRHkd+9YVZHbi8mavrOl09h80LPWipNMfRaPjgwGxyfsRhm8skTk+kDDYu8VV6aJEAf0xeQ9o+Wd58hJDjpxCfLejqW/Knzrs/1STJbYrLdv92q15vD33/jjTArC5zE/T93cjRnwXXM/l1gDP7fT0YI4VkRcz4cX5fuLiv1ElvaurePYC/ojeZbjjJNt6siSMZHa/Ts0CdITfRxdCbMD7IJs1i9enov6/cpPJgc9sm1Y4bDisCn5nWaICIMCvVO6mP8UtgQK1tuDLvBvFNcB0Dfj0csi8WvYmyD38ysgJODsJYK4Uao7Tus0Npia9Hi6hmsRZyspwWWt7KcWuGhV1KKHbaVb/I94TJMytzbJ4okTYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099pZ8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYp1syBl35C5gqYkurA0fulMKRW3ogFzQm6zN0ubto4HLSu96+u/unXqMVKybRYm2dMuSO3YlYJQYsvlwNjyG3+BqiXWrMqq8iecJW6e/aebzFeobGV5GKOfOAgCA2jAfJx9WgvamxqsAswzXoNHcblClc9sWR7PfIBfUUlO3cgU6mY5qN7o1c6REK8u4E3YBfeWt6Ga4MIESaOi3eacKwUdjrrduRteSYoc/zjvNvgQK8yy+Ll9LZOgT+lvn2Jl3hcPC0WZPl7oqpqvitKBJoBqNe8dSiyrRHkd+9YVZHbi8mavrOl09h80LPWipNMfRaPjgwGxyfsRhm8skTk+kDDYu8VV6aJEAf0xeQ9o+Wd58hJDjpxCfLejqW/Knznd/1STJbYrLdv92q15vD33/jjTArC5zE/T93cjRnwXXM/l1gDP7fT0YI4VkRcz4cX5fuLiv1ElvaurePYC/ojeZbjjJNt6siSMZHa/Ts0CdITfRxdCbMD7IJs1i9enov6/cpPJgc9sm1Y4bDisCn5nWaICIMCvVO6mP8UtgQK1tuDLvBvFNcB0Dfj0csi8WvYmyD38ysgJODsJYK4Uao7Tus0Npia9Hi6hmsRZyspwWWt7KcWuGhV1KKHbaVb/I94TJMytzbJ4okTYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099pZ8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYp1syBl35C5gqYkurA0fulMKRW3ogFzQm6zN0ubto4HLSu96+u/unXqMVKybRYm2dMuSO3YlYJQYsvlwNjyG3+BqiXWrMqq8iecJW6e/aebzFeobGV5GKOfOAgCA2jAfJx9WgvamxqsAswzXoNHcblClc9sWR7PfIBfUUlO3cgU6mY5qN7o1c6REKally4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099pZ8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYp1syBl35C5gqYkurA0fulMKRW3ogFzQm6zN0ubto4HLSu96+u/unXqMVKybRYm2dMuSO3YlYJQYsvlwNjyG3+BqiXWrMqq8iecJW6e/aebzFeobGV5GKOfOAgCA2jAfJx9WgvamxqsAswzXoNHcblClc9sWR7PfIBfUUlO3cgU6mY5qN7o1c6REK8u4E3YBfeWt6Ga4MIESaOi3eacKwUdjrrduRteSYoc/zjvNvgQK8yy+Ll9LZOgT+lvn2Jl3hcPC0WZPl7oqpqvitKBJoBqNe8dSiyrRHkd+9YVZHbi8mavrOl09h80LPWipNMfRaPjgwGxyfsRhm8skTk+kDDYu8VV6aJEAf0xeQ9o+Wd58hJDjpxCfLejqW/Knznd/1STJbYrLdv92q15vD33/jjTArC5zE/T93cjRnwXXM/l1gDP7fT0YI4VkRcz4cX5fuLiv1ElvaurePYC/ojeZbjjJNt6siSMZHa/Ts0CdITfRxdCbMD7IJs1i9enov6/cpPJgc9sm1Y4bDisCn5nWaICIMCvVO6mP8UtgQK1tuDLvBvFNcB0Dfj0csi8WvYmyD38ysgJODsJYK4Uao7Tus0Npia9Hi6hmsRZyspwWWt7KcWuGhV1KKHbaVb/I94TJMytzbJ4okTYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099pZ8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYp1syBl35C5gqYkurA0fulMKRW3ogFzQm6zN0ubto4HLSu96+u/unXqMVKybRYm2dMuSO3YlYJQYsvlwNjyG3+BqiXWrMqq8iecJW6e/aebzFeobGV5GKOfOAgCA2jAfJx9WgvamxqsAswzXoNHcblClc9sWR7PfIBfUUlO3cgU6mY5qN7o1c6REK8u4E3YBfeWt6Ga4MIESaOi3eacKwUdjrrduRteSYoc/zjvNvgQK8yy+Ll9LZOgT+lvn2Jl3hcPC0WZPl7oqpqvitKBJoBqNe8dSiyrRHkd+9YVZHbi8mavrOl09h80LPWipNMfRaPjgwGxyfsRhm8skTk+kDDYu8VV6aJEAf0xeQ9o+Wd58hJDjpxCfLejqW/Knznd/1STJbYrLdv92q15vD33/jjTArC5zE/T93cjRnwXXM/l1gDP7fT0YI4VkRcz4cX5fuLiv1ElvaurePYC/ojeZbjjJNt6siSMZHa/Ts0CdITfRxdCbMD7IJs1i9enov6/cpPJgc9sm1Y4bDisCn5nWaICIMCvVO6mP8UtgQK1tuDLvBvFNcB0Dfj0csi8WvYmyD38ysgJODsJYK4Uao7Tus0Npia9Hi6hmsRZyspwWWt7KcWuGhV1KKHbaVb/I94TJMytzbJ4okTYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099pZ8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYp1syBl35C5gqYkurA0fulMKRW3ogFzQm6zN0ubto4HLSu96+u/unXqMVKybRYm2dMuSO3YlYJQYsvlwNjyG3+BqiXWrMqq8iecJW6e/aebzFeobGV5GKOfOAgCA2jAfJx9WgvamxqsAswzXoNHcblClc9sWR7PfIBfUUlO3cgU6mY5qN7o1c6REK8u4E3YBfeWt6Ga4MIESaOi3eacKwUdjrrduRteSYoc/zjvNvgQK8yy+Ll9LZOgT+lvn2Jl3hcPC0WZPl7oqpqvitKBJoBqNe8dSiyrRHkd+9YVZHbi8mavrOl09h80LPWipNMfRaPjgwGxyfsRhm8skTk+kDDYu8VV6aJEAf0xeQ9o+Wd58hJDjpxCfLejqW/Knznd/1STJbYrLdv92q15vD33/jjTArC5zE/T93cjRnwXXM/l1gDP7fT0YI4VkRcz4cX5fuLiv1ElvaurePYC/ojeZbjjJNt6siSMZHa/Ts0CdITfRxdCbMD7IJs1i9enov6/cpPJgc9sm1Y4bDisCn5nWaICIMCvVO6mP8UtgQK1tuDLvBvFNcB0Dfj0csi8WvYmyD38ysgJODsJYK4Uao7Tus0Npia9Hi6hmsRZyspwWWt7KcWuGhV1KKHbaVb/I94TJMytzbJ4okTYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099pZ8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYp1syBl35C5gqYkurA0fulMKRW3ogFzQm6zN0ubto4HLSu96+u/unXqMVKybRYm2dMuSO3YlYJQYsvlwNjyG3+BqiXWrMqq8iecJW6e/aebzFeobGV5GKOfOAgCA2jAfJx9WgvamxqsAswzXoNHcblClc9sWR7PfIBfUUlO3cgU6mY5qN7o1c6REK8u4E3YBfeWt6Ga4MIESaOi3eacKwUdjrrduRteSYoc/zjvNvgQK8yy+Ll9LZOgT+lvn2Jl3hcPC0WZPl7oqpqvitKBJoBqNe8dSiyrRHkd+9YVZHbi8mavrOl09h80LPWipNMfRaPjgwGxyfsRhm8skTk+kDDYu8VV6aJEAf0xeQ9o+Wd58hJDjpxCfLejqW/Knznd/1STJbYrLdv92q15vD33/jjTArC5zE/T93cjRnwXXM/l1gDP7fT0YI4VkRcz4cX5fuLiv1ElvaurePYC/ojeZbjjJNt6siSMZHa/Ts0CdITfRxdCbMD7IJs1i9enov6/cpPJgc9sm1Y4bDisCn5nWaICIMCvVO6mP8UtgQK1tuDLvBvFNcB0Dfj0csi8WvYmyD38ysgJODsJYK4Uao7Tus0Npia9Hi6hmsRZyspwWWt7KcWuGhV1KKHbaVb/I94TJMytzbJ4okTYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099pZ8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYp1syBl35C5gqYkurA0fulMKRW3ogFzQm6zN0ubto4HLSu96+u/unXqMVKybRYm2dMuSO3YlYJQYsvlwNjyG3+BqiXWrMqq8iecJW6e/aebzFeobGV5GKOfOAgCA2jAfJx9WgvamxqsAswzXoNHcblClc9sWR7PfIBfUUlO3cgU6mY5qN7o1c6REK8u4E3YBfeWt6Ga4MIESaOi3eacKwUdjrrduRteSYoc/zjvNvgQK8yy+Ll9LZOgT+lvn2Jl3hcPC0WZPl7oqpqvitKBJoBqNe8dSiyrRHkd+9YVZHbi8mavrOl09h80LPWipNMfRaPjgwGxyfsRhm8skTk+kDDYu8VV6aJEAf0xeQ9o+Wd58hJDjpxCfLejqW/Knznd/1STJbYrLdv92q15vD33/jjTArC5zE/T93cjRnwXXM/l1gDP7fT0YI4VkRcz4cX5fuLiv1ElvaurePYC/ojeZbjjJNt6siSMZHa/Ts0CdITfRxdCbMD7IJs1i9enov6/cpPJgc9sm1Y4bDisCn5nWaICIMCvVO6mP8UtgQK1tuDLvBvFNcB0Dfj0csi8WvYmyD38ysgJODsJYK4Uao7Tus0Npia9Hi6hmsRZyspwWWt7KcWuGhV1KKHbaVb/I94TJMytzbJ4okTYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099pZ8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYp1syBl35C5gqYkurA0fulMKRW3ogFzQm6zN0ubto4HLSu96+u/unXqMVKybRYm2dMuSO3YlYJQYsvlwNjyG3+BqiXWrMqq8iecJW6e/aebzFeobGV5GKOfOAgCA2jAfJx9WgvamxqsAswzXoNHcblClc9sWR7PfIBfUUlO3cgU6mY5qN7o1c6REK8u4E3YBfeWt6Ga4MIESaOi3eacKwUdjrrduRteSYoc/zjvNvgQK8yy+Ll9LZOgT+lvn2Jl3hcPC0WZPl7oqpqvitKBJoBqNe8dSiyrRHkd+9YVZHbi8mavrOl09h80LPWipNMfRoPjgwGxyfsRhm8skTk+kDDYu8VV6aJEAf0xeQ9o+Wd58hJDjpxCfLejqW/Knznd/1STJbYrLdv92q15vD33/jjTArC5zE/T93cjRnwXXM/l1gDP7fT0YI4VkRcz4cX5fuLiv1ElvaurePYC/ojeZbjjJNt6siSMZHa/Ts0CdITfRxdCbMD7IJs1i9enov6/cpPJgc9sm1Y4bDisCn5nWaICIMCvVO6mP8UtgQK1tuDLvBvFNcB0Dfj0csi8WvYmyD38ysgJODsJYK4Uao7Tus0Npia9Hi6hmsRZyspwWWt7KcWuGhV1KKHbaVb/I94TJMytzbJ4okTYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099pZ8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYp1syBl35C5gqYkurA0fulMKRW3ogFzQm6zN0ubto4HLSu96+u/unXqMVKybRYm2dMuSO3YlYJQYsvlwNjyG3+BqiXWrMqq8iecJW6e/aebzFeobGV5GKOfOAgCA2jAfJx9WgvamxqsAswzXoNHcblClc9sWR7PfIBfUUlO3cgU6mY5qN7o1c6REK8u4E3YBfeWt6Ga4MIESaOi3eacKwUdjrrduRteSYoc/zjvNvgQK8yy+Ll9LZOgT+lvn2Jl3hcPC0WZPl7oqpqvitKBJoBqNe8dSiyrRHkd+9YVZHbi8mavrOl09h80LPWipNMfRaPjgwGxyfsRhm8skTk+kDDYu8VV6aJEAf0xeQ9o+Wd58hJDjpxCfLejqW/Knznd/1STJbYrLdv92q15vD33/jjTArC5zE/T93cjRnwXXM/l1gDP7fT0YI4VkRcz4cX5fuLiv1ElvaurePYC/ojeZbjjJNt6siSMZHa/Ts0CdITfRxdCbMD7IJs1i9enov6/cpPJgc9sm1Y4bDisCn5nWaICIMCvVO6mP8UtgQK1tuDLvBvFNcB0Dfj0csi8WvYmyD38ysgJODsJYK4Uao7Tus0Npia9Hi6hmsRZyspwWWt7KcWuGhV1KKHbaVb/I94TJMytzbJ4okTYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099pZ8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYp1syBl35C5gqYkurA0fulMKRW3ogFzQm6zN0ubto4HLSu96+u/unXqMVKybRYm2dMuSO3YlYJQYsvlwNjyG3+BqiXWrMqq8iecJW6e/aebzFeobGV5GKOfOAgCA2jAfJx9WgvamxqsAswzXoNHcblClc9sWR7PfIBfUUlO3cgU6mY5qN7o1c6REK8u4E3YBfeWt6Ga4MIESaOi3eacKwUdjrrduRteSYoc/zjvNvgQK8yy+Ll9LZOgT+lvn2Jl3hcPC0WZPl7oqpqvitKBJoBqNe8dSiyrRHkd+9YVZHbi8mavrOl09h80LPWipNMfRaPjgwGxyfsRhm8skTk+kDDYu8VV6aJEAf0xeQ9o+Wd58hJDjpxCfLejqW/Knznd/1STJbYrLdv92q15vD33/jjTArC5zE/T93cjRnwXXM/l1gDP7fT0YI4VkRcz4cX5fuLiv1ElvaurePYC/ojeZbjjJNt6siSMZHa/Ts0CdITfRxdCbMD7IJs1i9enov6/cpPJgc9sm1Y4bDisCn5nWaICIMCvVO6mP8UtgQK1tuDLvBvFNcB0Dfj0csi8WvYmyD38ysgJODsJYK4Uao7Tus0Npia9Hi6hmsRZyspwWWt7KcWuGhV1KKHbaVb/I94TJMytzbJ4okTYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099pZ8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYp1syBl35C5gqYkurA0fulMKRW3ogFzQm6zN0ubto4HLSu96+u/unXqMVKybRYm2dMuSO3YlYJQYsvlwNjyG3+BqiXWrMqq8iecJW6e/aebzFeobGV5GKOfOAgCA2jAfJx9WgvamxqsAswzXoNHcblClc9sWR7PfIBfUUlO3cgU6mY5qN7o1c6REK8u4E3YBfeWt6Ga4MIESaOi3eacKwUdjrrduRteSYoc/zjvNvgQK8yy+Ll9LZOgT+lvn2Jl3hcPC0WZPl7oqpqvitKBJoBqNe8dSiyrRHkd+9YVZHbi8mavrOl09h85LPWipNMfRaPjgwGxyfsRhm8skTk+kDDYu8VV6aJEAf0xeQ9o+Wd58hJDjpxCfLejqW/Knznd/1STJbYrLdv92q15vD33/jjTArC5zE/T93cjRnwXXM/l1gDP7fT0YI4VkRcz4cX5fuLiv1ElvaurePYC/ojeZbjjJNt6siSMZHa/Ts0CdITfRxdCbMD7IJs1i9enov6/cpPJgc9sm1Y4bDisCn5nWaICIMCvVO6mP8UtgQK1tuDLvBvFNcB0Dfj0csi8WvYmyD38ysgJODsJYK4Uao7Tus0Npia9Hi6hmsRZyspwWWt7KcWuGhV1KKHbaVb/I94TJMytzbJ4okTYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099pZ8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYp1syBl35C5gqYkurA0fulMKRW3ogFzQm6zN0ubto4HLSu96+u/unXqMVKybRYm2dMuSO3YlYJQYsvlwNjyG3+BqiXWrMqq8iecJW6e/aebzFeobGV5GKOfOAgCA2jAfJx9WgvamxqsAswzXoNHcblClc9sWR7PfIBfUUlO3cgU6mY5qN7o1c6REK8u4E3YBfeWt6Ga4MIESaOi3eacKwUdjrrduRteSYoc/zjvNvgQK8yy+Ll9LZOgT+lvn2Jl3hcPC0WZPl7oqpqvitKBJoBqNe8dSiyrRHkd+9YVZHbi8mavrOl09h80LPWipNMfRaPjgwGxyfsRhm8skTk+kDDYu8VV6aJEAf0xeQ9o+Wd58hJDjpxCfLejqW/Knznd/1STJbYrLdv92q15vD33/jjTArC5zE/T93cjRnwXXM/l1gDP7fT0YI4VkRcz4cX5fuLiv1ElvaurePYC/ojeZbjjJNt6siSMZHa/Ts0CdITfRxdCbMD7IJs1i9enov6/cpPJgc9sm1Y4bDisCn5nWaICIMCvVO6mP8UtgQK1tuDLvBvFNcB0Dfj0csi8WvYmyD38ysgJODsJYK4Uao7Tus0Npia9Hi6hmsRZyspwWWt7KcWuGhV1KKHbaVb/I94TJMytzbJ4okTYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099Z8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099Z8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099Z8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099Z8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099Z8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099Z8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1JUUdizjTZqmmgryd8J1ZTzY+62+WXqUNK7NGlJ1QQeI98IJABeeMETsGjy1lx4ONtfMM9LqnbSd5McDf+5EpszsrUlxvJaWtGlaPXJHFvmedR2VbWpitSFcdVOwU0vj5HFL4MEiMxgJIu2kE+H9rvYKQhCQhq9XojYdCzQ7m73NIuwqiohnVXOClBlBCb+FmmEo6HWTo0tXXG9LnjEUSjIV56j4RTOWeh8zjvNZG6L10QHgNY9TZ5JrCwDXuQyPfQ3UALlDUABDfYcnPf9qxkIW2tbtxReDCmb7oGPymuoHnZ1EsLtYQ+D6iqBKjFt8AGMwoW0yjnlgHWlfIHBGpHxylBBTWcHaRwc6N1IyvYPiC099Z8JsPxLYyMwMV8hXdtrU7nSLsCs+rkECrLJt8YqUY2u1eI/r/lrPKFPR0eDvtR8JSEGWnVx4DE6KVRjBRT4RZ1FwJI150hyPhvRYUEtqNUuLqY8L4xRAsokseOJIfgBBSEZdYpSojRKqFculrjXBEa7HFtxWEE8GmDm9HywZxB/xP0EHXxa1gAssKSwzmWdMVqcnH95NBMcl6ikm4AtVg4IYIQjBJuXg4OYtrmF1YlPhDVliGbyDQtkzo9NsB4DwiMI621JhGVyZ+fxJEb84pO7dPQP09dOJelkUXsDAxgTCc5APBRDdSZs7GHIJBehtBARpSA+pofT4x/Wq+5IxNG735dONI85gU/vOZGbcnxyDnSQe1//YnIjmHAojaryZZ0boyjUpCSQ/Pp+bca09w0CSJ5imGyHGKMer4yrVDKTJ7Gnjh+vTFXcW9D7gGYQpsJDykfMOTYkH2XEpyhTlVZP981uparBSsNVun/rdullXqrvw1XIr5SzP4ET4+/88D+V+kLR78v0qKpDmIpGcT1SVUWcPjHxGihnkIJEOMAZ7jEXwC3w080iimfcKywGTFaQVzn7zpAugYGoD/9/XOQnd0qZ/SR7goo3KIVo99Tf3nI76WfmDo3gXxI6WtoYvgCr31SzvExePHV2I2MuS0YaiE0ql5h9Y4Jbx7D0k0TP6KnvewaQ2wNOX9oz0hTuyMu/ZtcJQAbzWqj5GupbpdZfeb/z8Kai9JwTHgKGqDFSyp2fMbs9VKW16x1UuuXtEkca0gCHsEDeTyoDnOfYdqvESPkB/+aO7XQlWDzeq0xLq+Ysi4dou7IDDbFgMiVOHFjTolwK9CbvkkR0L9YmOQc7gP+Npx0XRObxZE1dUTvGt6Ju1cMrDE+SLqN/rYrer4hv2Zw/z7Xl7UzrB7xFjfWAfpl/sILFmyiP/o80Bf8BhjFWE4GbTaipPsOFmjgFHZyuB35G85DWX9gl73pFhj00f+wzJYJ2vpZ7GBg2fy9YPE44SHPphnkjV8JfBjvQoHKFrr5699e+jb/mqPcEp30XRObxZE1dUTvGt6Ju1cMrDE+SLqN/rYrer4hv2Zw/z7Xl7UzrB7xFjfWAfpl/sILFmyiP/o80Bf8BhjFWE4GbTaipPsOFmjgFHZyuB35G85DWX9gl73pFhj00f+wzJYJ2fy9YPE44SHPphnkjV8JfBjvQoHKFrr5699e+jb/mqPcEp30XRObxZE1dUTvGt6Ju1cMrDE+SLqN/rYrer4hv2Zw/z7Xl7UzrB7xFjfWAfpl/sILFmyiP/o80Bf8BhjFWE4GbTaipPsOFmjgFHZyuB35G85DWX9gl73pFhj00f+wzJYJ2ways1dUqTdH9pG0BsBdiecHOWnNdYL1Gj0Jiw6aoWDPsn9T9Uwb7y9fcUdE6aVr/FOoiIUpcgeJjDXV1cYlDFdogMmE97ZQnV4i6crfSh6QjEjoAD+lxGeLBCGeWebW+6YFMvreMwhxrDjhxwxtJB+dCtEeeYiZYOsrxyUYC7/xm2ONYQjmYXHI32DUG2PAd0aTvIVLVtzTdRpoYnoNcJNo+1IsDUQ06PvmXvqKdA8qpsBqtotOtLJLGYNx/uU2c64r4/mFSO7XEG/SwjOF/rCghL9NgdExl3zHoTnkshudv5w8mjRueD76j0gmldXJr4/7it3WgxBUsrJhRBXSBkyOGp7PFLDL/HrNziF0bk63JuPZQKpEaCCUCwSqsf3F+PkAXX6kSqV3M+gYwei7/cBnTyqa8t1VCusFrVGTUzTS0DSMkFSK9ZFVq7LrQTeRZNFD9RF4m64vvBl3mHAUMtdg8JsXR1bwLkCifSxhZ6bftLj7vdu/T40RjI/GFg5MKlIaCiCdX0jaVeDbGTczX1jPAQgmi6BZj9/lYwmBonPU07dK2h6oI9cfU6/I5k/CTNqZqoDgGPe5gAv2BAzwy8A3jUwrlASQ+N5IX0P9R6zyB2PV3fpl2dhrHTDDV52IKFC/4pPBskwN3QvBo4o7GWWDyzOWWpxbWOH6bGCYBQvk4Cl4O4lke6PoIOr8nukkLAoHkx2YHVbgI6pdiVpLumv4NC9zDaC1y311d0Oll8OsH2T6Nx7yyCTI245FNicdgjjmlA37eTzKpsFovnFLJz9eQgVblwbBfPAgY3Y7nNhjJ4Yk79lsDtqBXKaBMNijVTmmlNwbU56uF7PjRX7+o6O73qeptk0i/1qebSsHQsmujZ12Pw3qOuVFszDosTvRydvuG7C4EqyezoskwXe3Td8MpA+j+Pd2XaZReKXjHwpEkSmeRih49tw77QxyDdt9wTo5V/HLi4rMbYsiJHds9YjQsWcz5KkpBTvtDcf73HDN/eEmp7D36Zc9KluEPUX9ZIzFfkctbRS/GUfrzBThZq6GfU9ovcukT7v6ifORJBDCnWYc9DXb56dbzfvhhR50rjB+98H1iOakqxcaJVUCxWjdXkQ8uc82RkpwPRPDwHFZ7kWPoJy041HQgm4MgS3LVR8eCtd5mfBiBcr9RK1ZFydijOfvu60Yq7Nx7UySSSHdSZ+sYhJfFkH+Af3DKm65sGEws9c3m5WrY/aUvskKgVrHm+EvrIGsCkxgCU1Y2A7q8siezM1qqISTV1YbNnmxiMKJ0k3JM2gb2JpS2wNA='

interface City {
  name: string
  x: number // Percentual 0..1
  y: number // Percentual 0..1
  side: 'west' | 'east'
  isDestroyed: boolean
  destroyedTime: number
}

interface Missile {
  id: number
  from: { x: number; y: number }
  to: { x: number; y: number }
  fromName: string
  toName: string
  progress: number // 0..1
  speed: number
  active: boolean
  trail: { x: number; y: number }[]
  type: 'icbm' | 'abm' // icbm = offensive, abm = defensive interceptor
  targetMissile?: Missile // target for ABMs
  color: string
}

interface ImpactRipple {
  x: number
  y: number
  r: number
  maxR: number
  alpha: number
  color: string
}

interface Particle {
  x: number
  y: number
  vx: number
  vy: number
  alpha: number
  size: number
  color: string
}

const CITIES: City[] = [
  { name: 'WASHINGTON D.C.', x: 0.28, y: 0.44, side: 'west', isDestroyed: false, destroyedTime: 0 },
  { name: 'NEW YORK', x: 0.29, y: 0.42, side: 'west', isDestroyed: false, destroyedTime: 0 },
  { name: 'CHICAGO', x: 0.26, y: 0.42, side: 'west', isDestroyed: false, destroyedTime: 0 },
  { name: 'SAN FRANCISCO', x: 0.16, y: 0.46, side: 'west', isDestroyed: false, destroyedTime: 0 },
  { name: 'LONDON', x: 0.48, y: 0.36, side: 'west', isDestroyed: false, destroyedTime: 0 },
  { name: 'PARIS', x: 0.50, y: 0.38, side: 'west', isDestroyed: false, destroyedTime: 0 },
  { name: 'MOSCOW', x: 0.60, y: 0.35, side: 'east', isDestroyed: false, destroyedTime: 0 },
  { name: 'BEIJING', x: 0.78, y: 0.42, side: 'east', isDestroyed: false, destroyedTime: 0 },
  { name: 'TOKYO', x: 0.84, y: 0.44, side: 'east', isDestroyed: false, destroyedTime: 0 },
  { name: 'SIBERIA MILITARY BASE', x: 0.68, y: 0.32, side: 'east', isDestroyed: false, destroyedTime: 0 },
  { name: 'MONTANA SILO COMPLEX', x: 0.22, y: 0.39, side: 'west', isDestroyed: false, destroyedTime: 0 },
  { name: 'URAL LAUNCH COMPLEX', x: 0.64, y: 0.34, side: 'east', isDestroyed: false, destroyedTime: 0 },
]

function ThermonuclearWarPanel() {
  const containerRef = useRef<HTMLDivElement>(null)
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const [logs, setLogs] = useState<string[]>([])
  
  // HUD state variables for visual readouts
  const [defcon, setDefcon] = useState(5)
  const [activeMissilesCount, setActiveMissilesCount] = useState(0)
  const [casualties, setCasualties] = useState(0)
  const [stageName, setStageName] = useState('PRE-LAUNCH DRILL')

  useEffect(() => {
    const _canvas = canvasRef.current
    const container = containerRef.current
    if (!_canvas || !container) return
    const _ctx = _canvas.getContext('2d')
    if (!_ctx) return
    const canvas: HTMLCanvasElement = _canvas
    const ctx: CanvasRenderingContext2D = _ctx

    // Cleanup-Funktion vom raf-coordinator
    let unsubscribe: (() => void) | null = null
    let alive = true
    // Erster Frame nach Subscribe initialisiert lastT, damit dt nicht riesig wird
    let firstFrame = true

    // Load and process Earth map
    const mapImg = new Image()
    let processedMap: HTMLCanvasElement | null = null
    
    mapImg.onload = () => {
      const offscreen = document.createElement('canvas')
      offscreen.width = mapImg.width
      offscreen.height = mapImg.height
      const oCtx = offscreen.getContext('2d')
      if (oCtx) {
        oCtx.drawImage(mapImg, 0, 0)
        const imgData = oCtx.getImageData(0, 0, offscreen.width, offscreen.height)
        const data = imgData.data

        for (let i = 0; i < data.length; i += 4) {
          const r = data[i]
          const g = data[i+1]
          
          if (r > 100) {
            // Blueprint landmasses in semi-transparent cyan-blue
            data[i]   = 0   // R
            data[i+1] = 95  // G
            data[i+2] = 200 // B
            data[i+3] = 95  // A
          } else if (g > 100) {
            // Tactical city nodes in glowing cyan-green
            data[i]   = 0   // R
            data[i+1] = 255 // G
            data[i+2] = 200 // B
            data[i+3] = 255 // A
          } else {
            // Oceans are fully transparent
            data[i+3] = 0
          }
        }
        oCtx.putImageData(imgData, 0, 0)
        processedMap = offscreen
      }
    }
    mapImg.src = `data:image/webp;base64,${EARTH_BASE64}`

    const resize = () => {
      canvas.width = container.clientWidth
      canvas.height = container.clientHeight
    }
    resize()
    const ro = new ResizeObserver(resize)
    ro.observe(container)

    // ── Simulation States (Refs for high performance rendering loop) ───────────────────
    const missilesRef = { current: [] as Missile[] }
    const ripplesRef = { current: [] as ImpactRipple[] }
    const particlesRef = { current: [] as Particle[] }
    
    let missileIdSeq = 0
    let simTime = 0.0
    let simStage = 0 // 0: Drill, 1: First Strike, 2: Retaliation, 3: Defensive ABMs, 4: Impact/Devastation, 5: Nuclear Winter
    let nextStageTimer = 6.0 // Sekunden
    let currentCasualties = 0
    let abmLaunchCooldown = 0.0

    // Reset simulation
    function resetSim() {
      missilesRef.current = []
      ripplesRef.current = []
      particlesRef.current = []
      currentCasualties = 0
      simStage = 0
      nextStageTimer = 6.0
      simTime = 0.0
      setDefcon(5)
      setCasualties(0)
      setStageName('TACTICAL DRILL')
      CITIES.forEach(c => {
        c.isDestroyed = false
        c.destroyedTime = 0
      })
      setLogs([
        `[${new Date().toTimeString().split(' ')[0]}] GLOBAL THERMONUCLEAR WAR SIMULATION REINITIALIZED.`,
        `[${new Date().toTimeString().split(' ')[0]}] RADAR FEED ACTIVE. DEFCON 5 SECURE.`
      ])
    }

    const addLog = (text: string) => {
      const now = new Date()
      const timeStr = `[${now.toTimeString().split(' ')[0]}]`
      setLogs(prev => [ `${timeStr} ${text}`, ...prev.slice(0, 14) ])
    }

    // Trigger launch from side to target
    function triggerICBMLaunch(fromCity: City, toCity: City, W: number, H: number, delayOffset = 0) {
      const fromX = fromCity.x * W
      const fromY = fromCity.y * H
      const toX = toCity.x * W
      const toY = toCity.y * H

      missilesRef.current.push({
        id: missileIdSeq++,
        from: { x: fromX, y: fromY },
        to: { x: toX, y: toY },
        fromName: fromCity.name,
        toName: toCity.name,
        progress: -delayOffset, // Negative progress allows delayed launches
        speed: 0.15 + Math.random() * 0.08,
        active: true,
        trail: [],
        type: 'icbm',
        color: 'rgba(255, 30, 80, 0.95)' // Red arc
      })
    }

    // Launch interceptor ABM from a friendly city towards an incoming ICBM
    function triggerABMLaunch(friendlyCity: City, targetMissile: Missile, W: number, H: number) {
      const fromX = friendlyCity.x * W
      const fromY = friendlyCity.y * H

      missilesRef.current.push({
        id: missileIdSeq++,
        from: { x: fromX, y: fromY },
        to: { x: targetMissile.from.x, y: targetMissile.from.y }, // Track back or meet
        fromName: friendlyCity.name,
        toName: `ICBM INTERCEPTOR #${targetMissile.id}`,
        progress: 0,
        speed: 0.35 + Math.random() * 0.1, // ABMs fly much faster
        active: true,
        trail: [],
        type: 'abm',
        targetMissile: targetMissile,
        color: 'rgba(0, 240, 255, 0.95)' // Cyan arc
      })
    }

    // Explode particles on interception or impact
    function spawnExplosion(x: number, y: number, count = 25, color = '#ff3344') {
      for (let i = 0; i < count; i++) {
        const angle = Math.random() * Math.PI * 2
        const spd = 20.0 + Math.random() * 120.0
        particlesRef.current.push({
          x,
          y,
          vx: Math.cos(angle) * spd,
          vy: Math.sin(angle) * spd,
          alpha: 1.0,
          size: 1.5 + Math.random() * 2.5,
          color
        })
      }
    }

    resetSim()

    // ── Animations-Loop ──────────────────────────────────────────────────────
    let lastT = 0

    function loop(t: number) {
      if (!alive) return

      // Erster Frame nach Subscribe: lastT initialisieren
      if (firstFrame) { lastT = t; firstFrame = false }

      const dt = Math.min((t - lastT) / 1000, 0.08)
      lastT = t
      simTime += dt

      const W = canvas.width
      const H = canvas.height
      if (W === 0 || H === 0) {
        return
      }

      // ── Simulation Stages State Machine ──────────────────────────────────────
      nextStageTimer -= dt
      if (nextStageTimer <= 0) {
        simStage = (simStage + 1) % 6
        if (simStage === 0) {
          resetSim()
        } else if (simStage === 1) {
          // FIRST STRIKE
          setDefcon(3)
          setStageName('FIRST STRIKE DETECTED')
          nextStageTimer = 4.0
          addLog('WARNING: THERMAL SENSORS DETECT MULTIPLE SILO IGNITIONS (EAST SQUADRONS).')
          
          const eastLaunchers = CITIES.filter(c => c.side === 'east')
          const westTargets = CITIES.filter(c => c.side === 'west')
          
          // Launch 5 missiles immediately
          for (let i = 0; i < 5; i++) {
            const from = eastLaunchers[i % eastLaunchers.length]
            const to = westTargets[Math.floor(Math.random() * westTargets.length)]
            triggerICBMLaunch(from, to, W, H, i * 0.1)
          }

          // West Coast immediately fires defensive ABMs at 2 of them
          setTimeout(() => {
            if (!alive) return
            const activeICBMs = missilesRef.current.filter(m => m.type === 'icbm' && m.active)
            const westDefenders = CITIES.filter(c => c.side === 'west' && !c.isDestroyed)
            for (let i = 0; i < Math.min(activeICBMs.length, 2); i++) {
              const launcher = westDefenders[i % westDefenders.length]
              if (launcher) {
                triggerABMLaunch(launcher, activeICBMs[i], W, H)
              }
            }
          }, 300)
        } else if (simStage === 2) {
          // RETALIATION
          setDefcon(2)
          setStageName('MASS RETALIATION STAGE')
          nextStageTimer = 6.0
          addLog('ALERT: DEFCON 2 ENFORCED. DEPLOYING FULL RETALIATORY RESPONSE VECTOR.')
          
          const east = CITIES.filter(c => c.side === 'east' && !c.isDestroyed)
          const west = CITIES.filter(c => c.side === 'west' && !c.isDestroyed)

          // West responds with 8 missiles
          west.forEach((from, idx) => {
            const target = east[idx % east.length]
            if (target) {
              triggerICBMLaunch(from, target, W, H, Math.random() * 0.2)
              triggerICBMLaunch(from, east[(idx + 1) % east.length], W, H, 0.2 + Math.random() * 0.2)
            }
          })
          
          // East sends secondary strike of 8 missiles
          east.forEach((from, idx) => {
            const target = west[idx % west.length]
            if (target) {
              triggerICBMLaunch(from, target, W, H, Math.random() * 0.2)
              triggerICBMLaunch(from, west[(idx + 1) % west.length], W, H, 0.2 + Math.random() * 0.2)
            }
          })
        } else if (simStage === 3) {
          // DEFENSIVE ENGAGEMENT (Launch interceptors)
          setDefcon(1)
          setStageName('DEFENSIVE ENGAGEMENT')
          nextStageTimer = 5.0
          addLog('ABM SHIELD: THREAT LEVEL CRITICAL. DISPATCHING ALL REMAINING SYSTEM ABMS.')

          // Find active ICBMs in air
          const activeICBMs = missilesRef.current.filter(m => m.type === 'icbm' && m.progress > 0 && m.progress < 0.8)
          const friendlyCities = CITIES.filter(c => !c.isDestroyed)

          activeICBMs.forEach((icbm, idx) => {
            // Find opposite side launcher
            const targetCity = CITIES.find(c => Math.hypot(c.x * W - icbm.to.x, c.y * H - icbm.to.y) < 15)
            if (targetCity) {
              const defenders = friendlyCities.filter(c => c.side === targetCity.side)
              const launcher = defenders[idx % defenders.length]
              if (launcher) {
                triggerABMLaunch(launcher, icbm, W, H)
              }
            }
          })
        } else if (simStage === 4) {
          // CONFLICT DEVASTATION
          setStageName('TERMINAL IMPACTS')
          nextStageTimer = 6.0
          addLog('TACTICAL DATA: EXTENSIVE WARHEAD ENTRIES AND CRATERING DETECTED.')
        } else if (simStage === 5) {
          // NUCLEAR WINTER
          setStageName('EXTINCTION STATE')
          nextStageTimer = 8.0
          addLog('CRITICAL CLIMATE MODEL: GLOBAL PARTICULATE INTRUSION EXCEEDS 95%. TEMP -35C.')
          addLog('SYSTEM CONCLUSION: NO WINNERS DETECTED. SIMULATION ENDED.')
        }
      }

      // Dynamic interceptor auto-launcher
      if (simStage >= 1 && simStage <= 4) {
        abmLaunchCooldown -= dt
        if (abmLaunchCooldown <= 0) {
          abmLaunchCooldown = 0.5 // Check/launch every 0.5 seconds
          
          const activeICBMs = missilesRef.current.filter(m => m.type === 'icbm' && m.progress > 0.15 && m.progress < 0.75)
          const targetedMissileIds = new Set(
            missilesRef.current
              .filter(m => m.type === 'abm' && m.targetMissile && m.targetMissile.active)
              .map(m => m.targetMissile!.id)
          )
          
          const untargetedICBMs = activeICBMs.filter(m => !targetedMissileIds.has(m.id))
          
          if (untargetedICBMs.length > 0) {
            const friendlyCities = CITIES.filter(c => !c.isDestroyed)
            const target = untargetedICBMs.sort((a, b) => b.progress - a.progress)[0]
            const targetCity = CITIES.find(c => Math.hypot(c.x * W - target.to.x, c.y * H - target.to.y) < 15)
            if (targetCity) {
              const defenders = friendlyCities.filter(c => c.side === targetCity.side)
              if (defenders.length > 0) {
                const launcher = defenders[Math.floor(Math.random() * defenders.length)]
                triggerABMLaunch(launcher, target, W, H)
                addLog(`SHIELD INTERCEPT: INTERCEPTOR FIRED FROM ${launcher.name}.`)
              }
            }
          }
        }
      }

      // Update DEFCON values based on active stages
      if (simStage >= 4 && defcon !== 1) setDefcon(1)

      // ── ICBM & ABM Simulation ─────────────────────────────────────────────────
      const missiles = missilesRef.current
      const ripples = ripplesRef.current

      for (let i = missiles.length - 1; i >= 0; i--) {
        const m = missiles[i]
        if (!m.active) continue

        m.progress += m.speed * dt
        
        // Calculate curve path
        const p = Math.max(0.0, Math.min(1.0, m.progress))
        const t1 = 1 - p
        const t2 = p

        // Arch height proportional to distance
        const midX = (m.from.x + m.to.x) / 2
        let archH = Math.abs(m.from.x - m.to.x) * 0.35 + 50
        if (m.type === 'abm') archH *= 0.45 // ABM interceptors fly lower/straighter

        const midY = Math.min(m.from.y, m.to.y) - archH
        const px = t1 * t1 * m.from.x + 2 * t1 * t2 * midX + t2 * t2 * m.to.x
        const py = t1 * t1 * m.from.y + 2 * t1 * t2 * midY + t2 * t2 * m.to.y

        // Track trail
        if (m.progress >= 0) {
          m.trail.push({ x: px, y: py })
          if (m.trail.length > 25) m.trail.shift()
        }

        // Check ABM interception logic
        if (m.type === 'abm' && m.targetMissile) {
          const target = m.targetMissile
          if (!target.active) {
            // Target was already destroyed, self-destruct abm
            m.active = false
            missiles.splice(i, 1)
            continue
          }

          // Calculate current head pos for both
          const headABM = m.trail[m.trail.length - 1]
          const headICBM = target.trail[target.trail.length - 1]

          if (headABM && headICBM) {
            const dist = Math.hypot(headABM.x - headICBM.x, headABM.y - headICBM.y)
            if (dist < 12.0) {
              // Interception!
              m.active = false
              target.active = false
              
              spawnExplosion(headICBM.x, headICBM.y, 22, '#00ffff')
              ripples.push({
                x: headICBM.x,
                y: headICBM.y,
                r: 0,
                maxR: 35,
                alpha: 1.0,
                color: 'rgba(0, 240, 255, 0.9)'
              })
              addLog(`INTERCEPT: ICBM THREAT NEUTRALIZED BY SHIELD OVER SECTOR.`)
              
              // Remove both
              missiles.splice(i, 1)
              const tIdx = missiles.indexOf(target)
              if (tIdx > -1) missiles.splice(tIdx, 1)
              continue
            }
          }
        }

        // Impact logic
        if (m.progress >= 1.0) {
          m.active = false
          
          if (m.type === 'icbm') {
            // Find targeted city and destroy it
            const targetCity = CITIES.find(c => Math.hypot(c.x * W - m.to.x, c.y * H - m.to.y) < 15)
            if (targetCity) {
              targetCity.isDestroyed = true
              targetCity.destroyedTime = t
              addLog(`IMPACT: DETONATION CONFIRMED OVER ${targetCity.name}.`)
            }

            // Spawn destructive explosion
            spawnExplosion(m.to.x, m.to.y, 45, '#ff4400')
            ripples.push({
              x: m.to.x,
              y: m.to.y,
              r: 0,
              maxR: 65,
              alpha: 1.0,
              color: 'rgba(255, 30, 80, 0.95)'
            })
            currentCasualties += Math.floor(15 + Math.random() * 45) // Millions
          }
          
          missiles.splice(i, 1)
        }
      }

      // Update active missile counter
      setActiveMissilesCount(missiles.filter(m => m.active && m.progress > 0).length)

      // ── Simulation Ripples ──────────────────────────────────────────────────
      for (let i = ripples.length - 1; i >= 0; i--) {
        const r = ripples[i]
        r.r += 75.0 * dt
        r.alpha = 1.0 - r.r / r.maxR
        if (r.r >= r.maxR) ripples.splice(i, 1)
      }

      // ── Particle Simulation ─────────────────────────────────────────────────
      const particles = particlesRef.current
      for (let i = particles.length - 1; i >= 0; i--) {
        const p = particles[i]
        p.x += p.vx * dt
        p.y += p.vy * dt
        p.vy += 85.0 * dt // Gravity pulling sparks down
        p.alpha -= dt * 1.3
        if (p.alpha <= 0) particles.splice(i, 1)
      }

      // Smoothly update casualty counter (in millions)
      if (casualties < currentCasualties) {
        setCasualties(curr => Math.min(currentCasualties, curr + Math.max(1, Math.round((currentCasualties - curr) * 0.1))))
      }

      // ── Drawing ────────────────────────────────────────────────────────────
      ctx.fillStyle = '#010408' // Dark blue void
      ctx.fillRect(0, 0, W, H)

      // 1. Grid
      ctx.strokeStyle = 'rgba(0, 110, 220, 0.04)'
      ctx.lineWidth = 0.5
      const gSize = 35
      ctx.beginPath()
      for (let x = 0; x < W; x += gSize) {
        ctx.moveTo(x, 0); ctx.lineTo(x, H)
      }
      for (let y = 0; y < H; y += gSize) {
        ctx.moveTo(0, y); ctx.lineTo(W, y)
      }
      ctx.stroke()

      // 2. Blueprint Tactical processed map
      if (processedMap) {
        ctx.save()
        ctx.drawImage(processedMap, 0, 0, W, H)
        ctx.restore()
      }

      // 3. Expanding Detonation Ripples
      ripples.forEach(r => {
        ctx.save()
        ctx.strokeStyle = r.color
        ctx.lineWidth = 1.6
        ctx.beginPath()
        ctx.arc(r.x, r.y, r.r, 0, Math.PI * 2)
        ctx.stroke()
        
        ctx.fillStyle = r.color.replace('0.95', '0.1').replace('0.9', '0.1')
        ctx.beginPath()
        ctx.arc(r.x, r.y, r.r * 0.7, 0, Math.PI * 2)
        ctx.fill()
        ctx.restore()
      })

      // 4. Missile Trails
      missiles.forEach(m => {
        if (m.trail.length < 2) return

        ctx.save()
        const head = m.trail[m.trail.length - 1]
        
        const grad = ctx.createLinearGradient(m.trail[0].x, m.trail[0].y, head.x, head.y)
        grad.addColorStop(0, 'rgba(0,0,0,0)')
        grad.addColorStop(1, m.color)

        ctx.strokeStyle = grad
        ctx.lineWidth = m.type === 'abm' ? 1.0 : 1.6
        ctx.beginPath()
        ctx.moveTo(m.trail[0].x, m.trail[0].y)
        for (let j = 1; j < m.trail.length; j++) {
          ctx.lineTo(m.trail[j].x, m.trail[j].y)
        }
        ctx.stroke()

        // Glow head
        ctx.fillStyle = '#ffffff'
        ctx.shadowColor = m.type === 'abm' ? '#00ffff' : '#ff0033'
        ctx.shadowBlur = 6
        ctx.beginPath()
        ctx.arc(head.x, head.y, 2.2, 0, Math.PI * 2)
        ctx.fill()
        ctx.restore()
      })

      // 5. Fireball Sparks
      particles.forEach(p => {
        ctx.fillStyle = p.color
        ctx.globalAlpha = p.alpha
        ctx.fillRect(p.x - p.size/2, p.y - p.size/2, p.size, p.size)
      })
      ctx.globalAlpha = 1.0

      // 6. Draw City Targets (Launch points)
      CITIES.forEach(c => {
        const cx = c.x * W
        const cy = c.y * H

        if (c.isDestroyed) {
          // Blinking nuclear target bracket for destroyed cities
          const blk = Math.floor(t / 250) % 2 === 0
          if (blk) {
            ctx.strokeStyle = 'rgba(255, 30, 80, 0.85)'
            ctx.lineWidth = 1.0
            ctx.strokeRect(cx - 6, cy - 6, 12, 12)
            
            ctx.fillStyle = '#ff1e3c'
            ctx.font = 'bold 8px monospace'
            ctx.textAlign = cx > W / 2 ? 'right' : 'left'
            ctx.fillText('TERMINATED', cx > W / 2 ? cx - 8 : cx + 8, cy - 3)
          }
        } else {
          // Normal active city dot
          const pulse = 1.0 + Math.sin(t * 0.007 + cx) * 0.25
          ctx.strokeStyle = c.side === 'west' ? 'rgba(0, 180, 255, 0.45)' : 'rgba(0, 255, 140, 0.45)'
          ctx.lineWidth = 0.8
          ctx.beginPath()
          ctx.arc(cx, cy, 5.0 * pulse, 0, Math.PI * 2)
          ctx.stroke()

          ctx.fillStyle = c.side === 'west' ? '#00c3ff' : '#00ff8c'
          ctx.beginPath()
          ctx.arc(cx, cy, 2.2, 0, Math.PI * 2)
          ctx.fill()
        }

        // Draw names
        ctx.fillStyle = c.isDestroyed ? 'rgba(255, 30, 80, 0.4)' : 'rgba(255, 255, 255, 0.55)'
        ctx.font = '8px monospace'
        ctx.textAlign = cx > W / 2 ? 'right' : 'left'
        ctx.fillText(c.name, cx > W / 2 ? cx - 8 : cx + 8, cy + 8)
      })

      // 7. Apocalypse Overlay (Static noise and frosty overlay in Stage 5)
      if (simStage === 5) {
        ctx.save()
        // Frosty tint
        ctx.fillStyle = `rgba(180, 220, 255, ${0.15 * Math.min(1.0, simTime % 11.0 / 2.0)})`
        ctx.fillRect(0, 0, W, H)

        // Static glitch lines
        ctx.strokeStyle = 'rgba(255, 255, 255, 0.07)'
        ctx.lineWidth = 1.0
        for (let i = 0; i < 4; i++) {
          const sy = Math.random() * H
          ctx.beginPath()
          ctx.moveTo(0, sy)
          ctx.lineTo(W, sy)
          ctx.stroke()
        }
        ctx.restore()

        // Blinking Core Message
        const blink = Math.floor(t / 400) % 2 === 0
        if (blink) {
          ctx.save()
          ctx.fillStyle = 'rgba(255, 30, 80, 0.95)'
          ctx.font = 'bold 16px monospace'
          ctx.textAlign = 'center'
          ctx.fillText('NO WINNERS // EXTINCTION THRESHOLD REACHED', W / 2, H * 0.48)
          ctx.font = 'bold 10px monospace'
          ctx.fillStyle = '#00ffff'
          ctx.fillText('A STRANGE GAME. THE ONLY WINNING MOVE IS NOT TO PLAY.', W / 2, H * 0.53)
          ctx.restore()
        }
      }

      // 8. Draw Title HUD
      ctx.fillStyle = 'rgba(255, 30, 80, 0.85)'
      ctx.font = 'bold 10px monospace'
      ctx.textAlign = 'left'
      ctx.fillText(`TACTICAL ALERT: DEFCON ${defcon}`, 12, 22)

      ctx.fillStyle = 'rgba(200, 220, 255, 0.6)'
      ctx.font = '9px monospace'
      ctx.fillText(`STATUS LEVEL   : ${stageName}`, 12, 36)
      ctx.fillText(`AIRBORNE ICBMS : ${activeMissilesCount}`, 12, 48)
      ctx.fillText(`EST. CASUALTIES: ${casualties} MILLION`, 12, 60)

      ctx.textAlign = 'right'
      ctx.fillText('GLOBAL DEFENSE MAINBOARD // WOPR', W - 12, 22)
      ctx.fillText('MAP SECTOR: PLANAR CYLINDRICAL (REAL)', W - 12, 36)
      ctx.fillText(`SIMULATOR TIME: ${simTime.toFixed(1)}S`, W - 12, 48)
    }

    // Beim zentralen raf-coordinator anmelden
    unsubscribe = subscribe(loop)

    return () => {
      alive = false
      if (unsubscribe) unsubscribe()
      ro.disconnect()
    }
  }, [])

  return (
    <Panel title="GLOBAL TELEMETRY // WOPR WAR SIMULATION">
      <div ref={containerRef} className="w-full h-full relative overflow-hidden flex flex-col bg-black">
        {/* Canvas für die Weltkarten-Physiksimulation */}
        <div className="flex-1 w-full relative">
          <canvas
            ref={canvasRef}
            style={{ width: '100%', height: '100%', display: 'block' }}
          />
        </div>
        
        {/* Unterer fiktiver Ticker (DEFCON / Kriegsverlauf) */}
        <div className="h-24 bg-red-950/20 border-t border-red-900/60 p-2 font-mono text-[8px] text-red-500 overflow-y-auto leading-relaxed flex flex-col-reverse select-none">
          {logs.map((log, idx) => (
            <div key={idx} className={idx === 0 ? 'text-red-400 font-bold animate-pulse' : 'text-red-700/80'}>
              {log}
            </div>
          ))}
        </div>
      </div>
    </Panel>
  )
}

export default memo(ThermonuclearWarPanel)
